blank_issues_enabled: false
contact_links:
  - name: GitHub Discussions
    url: https://github.com/materia-technologies-inc/chameleon/discussions
    about: For general discussions and community support
